# Generated by Django 4.0.1 on 2023-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_project_delete_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
